from sqlalchemy import Column, Integer, String, Date, Float, Text, JSON, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from datetime import datetime
import sys
import os

# Add parent dir to path to import database
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from database import Base

class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True)
    description = Column(Text, nullable=True)
    category_vector = Column(Vector(384))  # all-MiniLM-L6-v2 outputs 384 dimensions
    created_at = Column(DateTime, default=datetime.utcnow)

class Cluster(Base):
    __tablename__ = "clusters"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=True)  # Name generated by LLM
    keywords = Column(JSON)  # c-TF-IDF keywords
    created_at = Column(DateTime, default=datetime.utcnow)

    papers = relationship("Paper", back_populates="cluster")

class Paper(Base):
    __tablename__ = "papers"

    id = Column(Integer, primary_key=True, index=True)
    arxiv_id = Column(String, unique=True, index=True)
    title = Column(String)
    abstract = Column(Text)
    authors = Column(JSON)
    published = Column(Date)
    url = Column(String)
    
    # Vector for Zero-shot classification
    paper_vector = Column(Vector(384))
    
    # Coordinates for UMAP 2D projection
    umap_x = Column(Float, nullable=True)
    umap_y = Column(Float, nullable=True)
    
    # Clustering info
    cluster_id = Column(Integer, ForeignKey("clusters.id"), nullable=True)
    cluster = relationship("Cluster", back_populates="papers")
    
    created_at = Column(DateTime, default=datetime.utcnow)
